### ISSUE TITLE
Error: "Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400"

### ISSUE THREAD

**Issue by mmarthab** [aws-samples/pace-genai-demos#17]
Hi, 

Deploying this solution fails with error:

"Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; "

This is on the lambda layer resource. 

Please can you check this?

**Comment by ztanruan** [comment]
As of **12/11/2023**, the size of our lambda layer, which utilizes the latest version of LangChain, is approximately 211.3MB, well within AWS's size constraint of 262.144MB.

To resolve this issue, I recommend the following steps:

- Delete the Existing Lambda Layer Folder: Begin by removing the lambda_langchain_layer folder from your project. This action ensures that any corrupted or oversized files are cleared.
- Recreate the Layer: After deletion, recreate the lambda layer using the `deploy.sh` command. This process should generate a fresh, size-compliant layer with the necessary components. 
- Clean Docker Resources: It's also crucial to ensure that no residual Docker images or containers are occupying unnecessary space. Clean all running Docker images and containers to free up space and avoid any potential conflicts.

By following these steps, you should be able to deploy the lambda layer without encountering the size limit error. If the problem persists, please let me know, and we can explore further solutions.

**Comment by ztanruan** [comment]
Embeddings Chatbot is designed to be deployed locally and may not function correctly if deployed using Cloud9 or similar cloud-based development environments. To ensure full functionality and a smooth setup process, please follow the instructions inside the README file to deploy the demo locally on your own local machine.

**Comment by ztanruan** [comment]
An upgrade to the Lambda layer has been implemented. To access the latest version, please clone the latest code and execute the deployment steps outlined in the README document. At present, our Docker container build process for the Lambda layer is compatible exclusively with the Amd64 architecture. Future updates will extend support to X86 and Linux platforms.

**Comment by ztanruan** [comment]
An updated to the Lambda layer has been implemented. To access the latest version, please clone the latest code and execute the deployment steps outlined in the README document. At present, our Docker container build process for the Lambda layer is compatible exclusively with the Amd64 architecture. Future updates will extend support to X86 and Linux platforms.

**Comment by ztanruan** [comment]
An updated to the Lambda layer has been implemented. To access the latest version, please clone the latest code and execute the deployment steps outlined in the README document. At present, our Docker container build process for the Lambda layer is compatible exclusively with the Arm64 architecture. Future updates will extend support to X86 and Linux platforms.
