### ISSUE TITLE
embeddingsbedrockLangchainLayer54390634 Lambda too big

### ISSUE THREAD

**Issue by matskm** [aws-samples/pace-genai-demos#18]
I cloned the repo on 14/11/23, and from the tip of the main branch (commit hash: a01bb1bfbed4d107633b3b78d91dc92a8f993c16) tried to deploy the Embeddings-Foundational-LLM-ChatBot example.

But on the cloudformation deployment step in the guru-chatbot stack I ran into this error for the logical resource: embeddingsbedrockLangchainLayer54390634

`Resource handler returned message: "Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 5c2f3a4b-c0c9-48ba-ab7e-af70401b9f31; Proxy: null)" (RequestToken: 579e2a4b-d216-c234-1769-ff474b9ab1d3, HandlerErrorCode: GeneralServiceException)`

Which I think means this Lambda layer is >250MB in size unzipped.

Checked and its 302MB unzipped. Lots of large python libs:

du -h . | sort -hr | head -n 10
302M    .
 81M    ./botocore
 78M    ./botocore/data
 70M    ./faiss
 36M    ./numpy.libs
 35M    ./numpy
 19M    ./sqlalchemy
 18M    ./numpy/core
 16M    ./langchain
9.2M    ./pydantic

How might this be resolved/worked-around?

**Comment by ztanruan** [comment]
Please clone the latest code. We have updated the docker file. Currently, due to the package's size constraints, support is extended solely to the arm64 architecture. Efforts are underway to modify the library, aiming to circumvent the 250M restriction in Lambda.
